baseurl = "https://zetton110.github.io/blog/"
canonifyurls = true
languageCode = "ja"
title = "2020/12/05(土) セミナー補足資料"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
[permalinks]
    post = "/:section/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Mail"
    url = "https://docs.google.com/forms/d/e/1FAIpQLSexaqxkfxJMBnNV1elMQsJklw5TKJCMw5LNGggQQjpQElocPA/viewform"

[params]
    description = ""

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

[taxonomies]
tag = "tags"